<a href="https://colab.research.google.com/github/AtaOzkan/Ders/blob/main/101_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import torch
import numpy as np

In [15]:
numpy_array = np.random.rand(3,4)

tensor1 = torch.from_numpy(numpy_array)

print(tensor1, "\n")

tensor2=torch.tensor(numpy_array)
print(tensor2)

tensor([[0.7144, 0.0401, 0.3497, 0.6317],
        [0.5995, 0.2155, 0.8267, 0.6726],
        [0.8278, 0.3547, 0.3155, 0.5697]], dtype=torch.float64) 

tensor([[0.7144, 0.0401, 0.3497, 0.6317],
        [0.5995, 0.2155, 0.8267, 0.6726],
        [0.8278, 0.3547, 0.3155, 0.5697]], dtype=torch.float64)


In [4]:
torch_2d= torch.randn(4,5)
print(torch_2d)

tensor([[ 1.2552, -0.1335, -2.1317,  1.0749,  0.1042],
        [-1.3997,  1.8080, -0.0459,  0.1689,  0.4904],
        [-0.1698, -0.3652,  0.3795,  1.0802, -0.8292],
        [ 0.1400, -0.5683,  0.8871,  0.4694, -0.7793]])


In [7]:
torch_arange=torch.arange(5)
print(torch_arange)

print("")

torch_arange=torch.reshape(torch_arange,(5,1))
print(torch_arange)



tensor([0, 1, 2, 3, 4])

tensor([[0],
        [1],
        [2],
        [3],
        [4]])


In [9]:
torch_1= torch.tensor([1,2,3,4])
torch_2= torch.tensor([5,6,7,8])

a=torch.add(torch_1,torch_2)
print(a)

print("")

b=torch.sub(torch_1,torch_2)
print(b)
print("")


c=torch.mul(torch_1,torch_2)
print(c)
print("")

d=torch.div(torch_1,torch_2)
print(d)


tensor([ 6,  8, 10, 12])

tensor([-4, -4, -4, -4])

tensor([ 5, 12, 21, 32])

tensor([0.2000, 0.3333, 0.4286, 0.5000])
